name: Deploy APP

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

on:
  push:
    branches:
      - develop
    paths:
      - app/**

jobs:
  deploy-staging:
     runs-on: ubuntu-latest
     environment: 'Staging'
     env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    #  needs: build-and-test
     steps:
       - uses: actions/checkout@v4
       
       - name: Install Vercel CLI
         run: npm install --global vercel

       - name: Install Pnpm
         run: npm install -g pnpm
       
       - name: Pull Vercel Environment Information
         run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

       - name: Build Project
         run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
         
       - name: Deploy Project Artifacts
         run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
  
  deploy-production:
     runs-on: ubuntu-latest
     environment: 'Production'
     env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
     needs: deploy-staging
     steps:
       - uses: actions/checkout@v4
       
       - name: Install Vercel CLI
         run: npm install --global vercel

       - name: Install Pnpm
         run: npm install -g pnpm
       
       - name: Pull Vercel Environment Information
         run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

       - name: Build Project
         run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
         
       - name: Deploy Project Artifacts
         run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  open-pr-to-main:
    runs-on: 'ubuntu-latest'
    needs: deploy-production
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Create pull request
        uses: devops-infra/action-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'main'
          title: Automatic pull request
          assignee: ${{ github.actor }}
          label: automatic
          get_diff: true